### ISSUE TITLE
Exclude on edges (Analyze Particles)

### ISSUE THREAD

**Issue by edallort** [Eroglu-Lab/Syn_Bot#4]
Hi!

Very interesting code!

Is it possible to remove the option "Exclude on edges" on the Analyze particles step? I noticed that it is probably flagged on since the binary thresholded image at the end (saved in the output folder) is different from the manual thresholded one. 

![image](https://github.com/Eroglu-Lab/Syn_Bot/assets/126768531/b83ae90d-17f3-4c54-9b22-d8b86e6bed5b)

This may result in different marker area measuring and eventually puncta counting

![image](https://github.com/Eroglu-Lab/Syn_Bot/assets/126768531/13028903-69e8-4fdd-ae30-658a759b8420)

Thank you very much

**Comment by savagedude3** [comment]
Exclude on edges is the convention for most image analysis since it can lead to incorrect interpretation of objects on the edge of the image. For example, if you wanted to compute the percentage of presynaptic puncta that have a postsynaptic partner, you could accidentally count a presynaptic marker on the edge as not having a colocalization when it does actually have one that is beyond the field of view. 

All this aside, the change to include edges is not difficult to implement and I added it here [Syn_Bot_include_edges.ijm](https://github.com/Eroglu-Lab/Syn_Bot/blob/main/extra_code/Syn_Bot_include_edges.ijm). 

Best of luck with your analyses.
